trigger:
- stefano/feature/ci

jobs:

# LINUX
  - job: Ubuntu1604Build

    pool: 
      vmImage: Ubuntu-16.04

    steps:
    - script: make sysprep
      displayName: "Prepare the system, downloading and installing the necessary"

    - script: make -j3
      displayName: "Build osql-lts"
      env:
        SKIP_BENCHMARKS: 1

    - script: make test
      displayName: "Run tests"


  - job: Ubuntu1404Build

    pool:
      vmImage: Ubuntu-16.04

    container: trailofbits/osql-lts:ubuntu-14.04

    steps:
      - script: make sysprep
        displayName: "Prepare the system, downloading and installing the necessary"

      - script: make -j3
        displayName: "Build osql-lts"
        env:
          SKIP_BENCHMARKS: 1

      - script: make test
        displayName: "Run tests"


  - job: CentOS7Build

    pool:
      vmImage: Ubuntu-16.04

    container: trailofbits/osql-lts:centos-7

    steps:
      - script: make sysprep
        displayName: "Prepare the system, downloading and installing the necessary"

      - script: make -j3
        displayName: "Build osql-lts"
        env:
          SKIP_BENCHMARKS: 1

      - script: make test
        displayName: "Run tests"


  - job: WindowsServer2016

    pool:
      vmImage: vs2017-win2016

    steps:
      - powershell: tools\make-win64-dev-env.bat /skip-windows-sdk
        displayName: "Prepare the system, downloading and installing the necessary"

      - powershell: |
          mkdir build
          cd build
          cmake $(Build.SourcesDirectory) -G "Visual Studio 14 2015 Win64"
        workingDirectory: $(Build.BinariesDirectory)
        displayName: "Configure the build"

      - powershell: cmake --build . --config Release
        workingDirectory: $(Build.BinariesDirectory)/build
        displayName: "Build osql-lts"

      - powershell: cmake --build . --config Release --target test
        workingDirectory: $(Build.BinariesDirectory)/build
        displayName: "Run tests"
