trigger:
- stefano/feature/ci

jobs:

# # LINUX
#   - job: Ubuntu1604Build

#     pool: 
#       vmImage: Ubuntu-16.04

#     steps:
#     - script: make sysprep
#       displayName: "Prepare the system, downloading and installing the necessary"

#     - script: make -j3
#       displayName: "Build osql-lts"
#       env:
#         SKIP_BENCHMARKS: 1

#     - script: make test
#       displayName: "Run tests"


#   - job: Ubuntu1404Build

#     pool:
#       vmImage: Ubuntu-16.04

#     container: trailofbits/osql-lts:ubuntu-14.04

#     steps:
#       - script: make sysprep
#         displayName: "Prepare the system, downloading and installing the necessary"

#       - script: make -j3
#         displayName: "Build osql-lts"
#         env:
#           SKIP_BENCHMARKS: 1

#       - script: make test
#         displayName: "Run tests"


#   - job: CentOS7Build

#     pool:
#       vmImage: Ubuntu-16.04

#     container: trailofbits/osql-lts:centos-7

#     steps:
#       - script: make sysprep
#         displayName: "Prepare the system, downloading and installing the necessary"

#       - script: make -j3
#         displayName: "Build osql-lts"
#         env:
#           SKIP_BENCHMARKS: 1

#       - script: make test
#         displayName: "Run tests"


# WINDOWS
  - job: WindowsServer2016

    pool:
      vmImage: vs2017-win2016

    steps:
      - powershell: tools\make-win64-dev-env.bat -skip windows-sdk
        displayName: "Prepare the system, downloading and installing the necessary"

      - script: |
          mkdir build
          cd build
          call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
          cmake $(Build.SourcesDirectory) -G "Visual Studio 15 2017 Win64" -T v141,host=x64
        workingDirectory: $(Build.BinariesDirectory)
        displayName: "Configure the build"
        env:
          SKIP_BENCHMARKS: 1

      - script: |
          call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
          cmake --build . --config Release
        workingDirectory: $(Build.BinariesDirectory)/build
        displayName: "Build osql-lts"

      - script: |
          call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
          cmake --build . --config Release --target test
        workingDirectory: $(Build.BinariesDirectory)/build
        displayName: "Run tests"
