trigger:
- master

jobs:

# LINUX
  - job: Ubuntu1604Build

    pool:
      vmImage: Ubuntu-16.04

    steps:
    - script: make sysprep
      displayName: "Prepare the system, downloading and installing the necessary"

    - script: make -j3
      displayName: "Build osql"
      env:
        SKIP_BENCHMARKS: 1

    - script: /usr/local/osquery/bin/ctest --build-nocmake -V
      displayName: "Run tests"
      workingDirectory: $(Build.SourcesDirectory)/build/linux


  - job: CentOS7Build

    pool:
      vmImage: Ubuntu-16.04

    container: trailofbits/osql:centos-7

    steps:
      - script: make sysprep
        displayName: "Prepare the system, downloading and installing the necessary"

      - script: make -j3
        displayName: "Build osql"
        env:
          SKIP_BENCHMARKS: 1

      - script: /usr/local/osquery/bin/ctest --build-nocmake -V
        displayName: "Run tests"
        workingDirectory: $(Build.SourcesDirectory)/build/linux

  - job: CentOS6Build

    pool:
      vmImage: Ubuntu-16.04

    container: trailofbits/osql:centos-6

    steps:
      - script: make sysprep
        displayName: "Prepare the system, downloading and installing the necessary"

      - script: make -j3
        displayName: "Build osql"
        env:
          SKIP_BENCHMARKS: 1

      - script: /usr/local/osquery/bin/ctest --build-nocmake -V
        displayName: "Run tests"
        workingDirectory: $(Build.SourcesDirectory)/build/linux


# WINDOWS
  - job: WindowsServer2016Build

    pool:
      vmImage: vs2017-win2016

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '2.7'
          addToPath: true
          architecture: 'x64'

      - script: tools\make-win64-dev-env.bat -skip windows-sdk
        displayName: "Prepare the system, downloading and installing the necessary"

      - script: |
          mkdir build
          cd build
          call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
          cmake $(Build.SourcesDirectory) -G "Visual Studio 15 2017 Win64" -T v141,host=x64
        displayName: "Configure the build"
        workingDirectory: $(Build.BinariesDirectory)
        env:
          SKIP_BENCHMARKS: 1

      - script: |
          call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
          cmake --build . --config Release
        workingDirectory: $(Build.BinariesDirectory)/build
        displayName: "Build osql"

      - script: |
          call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
          ctest --build-nocmake -C Release -V
        displayName: "Run tests"
        workingDirectory: $(Build.BinariesDirectory)/build


# MACOS
  - job: macOS1013Build

    pool:
      vmImage: macos-10.13

    steps:
      - script: |
          unset HOMEBREW_NO_AUTO_UPDATE
          make sysprep
        displayName: "Prepare the system, downloading and installing the necessary"

      - script: make -j3
        displayName: "Build osql"
        env:
          SKIP_BENCHMARKS: 1

      - script: /usr/local/osquery/bin/ctest --build-nocmake -V
        displayName: "Run tests"
        workingDirectory: $(Build.SourcesDirectory)/build/darwin
